import { createApp } from 'vue';
import App from './App.vue';
import pinia from './store';
import router from './router';
// import ElementPlus from 'element-plus';
// import 'element-plus/dist/index.css';
import './styles/index.less';
import I18n from '@/languages/index';
const app = createApp(App);
app.use(router);
app.use(pinia);
app.use(I18n);
// app.use(ElementPlus);
app.mount('#app');
